/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Antigravity
-/
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Positivity

/-!
# Candidate 6: $\widetilde{\mathrm{SL}}_2(\mathbb{R})$ Geometry - Spectral Decomposition & Casimir Operators

This module formalizes the spectral decomposition of the Laplace-Beltrami operator on the
unit tangent bundle $T^1(\Sigma_g) \cong \widetilde{\Gamma}_g \backslash \widetilde{\mathrm{SL}}_2(\mathbb{R})$
over a closed hyperbolic surface $\Sigma_g$ of genus $g \ge 2$.

## Mathematical Summary

1. **Vertical Angular Momentum & Fiber Fourier Decomposition**:
   The unit tangent bundle $T^1(\Sigma_g)$ carries a free isometric $S^1 \cong \mathrm{SO}(2)$ action
   along its fibers generated by the vertical Killing vector field $E_3 = \partial_\theta$.
   The Hilbert space $L^2(T^1(\Sigma_g))$ decomposes orthogonally into vertical Fourier modes:
   $$L^2(T^1(\Sigma_g)) = \bigoplus_{m \in \mathbb{Z}} \mathcal{H}_m, \quad f(\theta, x) = \sum_{m \in \mathbb{Z}} f_m(x) e^{i m \theta}.$$
   On $\mathcal{H}_m$, the vertical Laplacian acts by multiplication by $m^2 / 4$ (with respect to
   the orthonormal frame normalization where $E_3 = 2 \partial_\theta$, or $-E_3^2 / 4$):
   $$-E_3^2 (e^{i m \theta}) = m^2 e^{i m \theta}.$$

2. **Casimir Operator & Joint Eigenvalues**:
   The Laplace-Beltrami operator $\Delta$ on $T^1(\Sigma_g)$ decomposes as the horizontal Casimir operator
   plus the vertical Casimir operator:
   $$\Delta = \Delta_{\Sigma_g} + \frac{1}{4} m^2.$$
   The joint eigenvalues labeled by base mode $j \in \mathbb{N}$ and vertical angular momentum $m \in \mathbb{Z}$ are:
   $$\lambda_{j, m} = \lambda_j(\Sigma_g) + \frac{m^2}{4}.$$

3. **Base Selberg Spectrum Connection ($m = 0$)**:
   The zero-angular-momentum sector $\mathcal{H}_0$ consists of functions invariant under fiber rotations,
   which are pullbacks of functions on the base surface $\Sigma_g$:
   $$\lambda_{j, 0} = \lambda_j(\Sigma_g).$$
   In particular:
   - Ground state: $\lambda_{0, 0} = \lambda_0(\Sigma_g) = 0$ (constant eigenfunctions).
   - First base eigenvalue: $\lambda_{1, 0} = \lambda_1(\Sigma_g) > 0$.

4. **Vertical Ground State ($j = 0, m = \pm 1$)**:
   The lowest non-trivial vertical excitation has eigenvalue:
   $$\lambda_{0, 1} = \lambda_0(\Sigma_g) + \frac{1^2}{4} = \frac{1}{4}.$$

5. **Spectral Gap Theorem on $T^1(\Sigma_g)$**:
   The first non-zero eigenvalue on the unit tangent bundle is strictly positive:
   $$\lambda_1(T^1(\Sigma_g)) = \min\left(\lambda_1(\Sigma_g), \, \frac{1}{4}\right) > 0.$$
   For all non-trivial pairs $(j, m) \ne (0, 0)$, $\lambda_{j, m} > 0$.
-/

namespace SL2RGeometry

/-! ### 1. Casimir & Laplace-Beltrami Eigenvalue Formula -/

/-- Joint Laplace-Beltrami / Casimir eigenvalue on $T^1(\Sigma_g)$ with base eigenvalue $\lambda_j \ge 0$
    and vertical angular momentum Fourier mode $m \in \mathbb{Z}$:
    $$\lambda_{j, m} = \lambda_j + \frac{m^2}{4}.$$ -/
noncomputable def casimirEigenvalue (lambda_base : ℝ) (m : ℤ) : ℝ :=
  lambda_base + (m : ℝ) ^ 2 / 4

/-- Vertical fiber contribution to the Casimir eigenvalue: $m^2 / 4$. -/
noncomputable def verticalEigenvalue (m : ℤ) : ℝ :=
  (m : ℝ) ^ 2 / 4

/-- Vertical eigenvalue is non-negative for all Fourier modes $m \in \mathbb{Z}$. -/
theorem verticalEigenvalue_nonneg (m : ℤ) : verticalEigenvalue m ≥ 0 := by
  dsimp [verticalEigenvalue]; positivity

/-- Vertical eigenvalue vanishes if and only if $m = 0$. -/
theorem verticalEigenvalue_eq_zero_iff (m : ℤ) :
    verticalEigenvalue m = 0 ↔ m = 0 := by
  dsimp [verticalEigenvalue]; simp

/-- Lowest non-zero vertical eigenvalue (achieved at $m = \pm 1$):
    $\lambda_{\mathrm{vert}, 1} = 1/4$. -/
noncomputable def verticalGroundState : ℝ := 1 / 4

/-- Mode $m = 1$ achieves the vertical ground state $1/4$. -/
theorem verticalEigenvalue_one : verticalEigenvalue 1 = verticalGroundState := by
  dsimp [verticalEigenvalue, verticalGroundState]; norm_num

/-- Mode $m = -1$ achieves the vertical ground state $1/4$. -/
theorem verticalEigenvalue_neg_one : verticalEigenvalue (-1) = verticalGroundState := by
  dsimp [verticalEigenvalue, verticalGroundState]; norm_num

/-- Vertical ground state is strictly positive: $1/4 > 0$. -/
theorem verticalGroundState_pos : verticalGroundState > 0 := by
  dsimp [verticalGroundState]; norm_num

/-! ### 2. Base Surface Spectrum & Selberg Connection ($m = 0$) -/

/-- Fiber-invariant mode ($m = 0$) recovers the exact base surface Laplace-Beltrami eigenvalue:
    $\lambda_{j, 0} = \lambda_j(\Sigma_g)$. -/
theorem casimirEigenvalue_fiber_invariant (lambda_base : ℝ) :
    casimirEigenvalue lambda_base 0 = lambda_base := by
  dsimp [casimirEigenvalue]; ring

/-- Ground state eigenvalue on the unit tangent bundle (constant mode $j = 0, m = 0$):
    $\lambda_{0, 0} = 0$. -/
theorem groundState_zero (lambda_0 : ℝ) (h0 : lambda_0 = 0) :
    casimirEigenvalue lambda_0 0 = 0 := by
  rw [casimirEigenvalue_fiber_invariant, h0]

/-- Parity symmetry: Casimir eigenvalues are invariant under vertical inversion $m \mapsto -m$. -/
theorem casimirEigenvalue_neg (lambda_base : ℝ) (m : ℤ) :
    casimirEigenvalue lambda_base (-m) = casimirEigenvalue lambda_base m := by
  dsimp [casimirEigenvalue]; push_cast; ring

/-! ### 3. Spectral Gap & Eigenvalue Positivity -/

/-- Non-negativity of Casimir eigenvalues for any non-negative base eigenvalue. -/
theorem casimirEigenvalue_nonneg {lambda_base : ℝ} (hbase : lambda_base ≥ 0) (m : ℤ) :
    casimirEigenvalue lambda_base m ≥ 0 := by
  dsimp [casimirEigenvalue]; positivity

/-- Strict positivity of Casimir eigenvalue when base eigenvalue is strictly positive. -/
theorem casimirEigenvalue_pos_of_base_pos {lambda_base : ℝ} (hbase : lambda_base > 0) (m : ℤ) :
    casimirEigenvalue lambda_base m > 0 := by
  dsimp [casimirEigenvalue]; positivity

/-- Strict positivity of Casimir eigenvalue when vertical mode $m \ne 0$. -/
theorem casimirEigenvalue_pos_of_mode_ne_zero {lambda_base : ℝ} (hbase : lambda_base ≥ 0)
    {m : ℤ} (hm : m ≠ 0) :
    casimirEigenvalue lambda_base m > 0 := by
  have : (m : ℝ) ≠ 0 := by exact_mod_cast hm
  dsimp [casimirEigenvalue]; positivity

/-- For any non-trivial state (either $\lambda_{\mathrm{base}} > 0$ or $m \ne 0$),
    the Casimir eigenvalue is strictly positive: $\lambda_{j, m} > 0$. -/
theorem casimirEigenvalue_pos_of_nontrivial {lambda_base : ℝ} (hbase : lambda_base ≥ 0)
    (m : ℤ) (h_nontrivial : lambda_base > 0 ∨ m ≠ 0) :
    casimirEigenvalue lambda_base m > 0 :=
  h_nontrivial.elim (casimirEigenvalue_pos_of_base_pos · m) (casimirEigenvalue_pos_of_mode_ne_zero hbase)

/-- First non-zero eigenvalue on $T^1(\Sigma_g)$ given base spectral gap $\lambda_1(\Sigma_g) > 0$:
    $$\lambda_1(T^1(\Sigma_g)) = \min(\lambda_1(\Sigma_g), \, 1/4).$$ -/
noncomputable def totalSpectralGap (lambda1_base : ℝ) : ℝ :=
  min lambda1_base verticalGroundState

/-- Total spectral gap is strictly positive whenever the base surface has positive spectral gap. -/
theorem totalSpectralGap_pos {lambda1_base : ℝ} (h_gap : lambda1_base > 0) :
    totalSpectralGap lambda1_base > 0 :=
  lt_min h_gap verticalGroundState_pos

/-- Any non-trivial mode with either base excitation $\lambda_{\mathrm{base}} \ge \lambda_1(\Sigma_g)$
    or vertical excitation $m \ne 0$ is bounded below by the total spectral gap $\min(\lambda_1, 1/4)$. -/
theorem casimirEigenvalue_ge_totalSpectralGap {lambda1_base : ℝ} (_h_gap : lambda1_base > 0)
    {lambda_base : ℝ} (hbase_nonneg : lambda_base ≥ 0) (m : ℤ)
    (h_excited : (lambda_base ≥ lambda1_base ∧ m = 0) ∨ (lambda_base ≥ 0 ∧ m ≠ 0)) :
    casimirEigenvalue lambda_base m ≥ totalSpectralGap lambda1_base := by
  dsimp [casimirEigenvalue, totalSpectralGap, verticalGroundState]
  rcases h_excited with ⟨hge, rfl⟩ | ⟨-, hm⟩
  · simpa using (min_le_left _ _).trans hge
  · have : (m : ℝ) ^ 2 ≥ 1 := by
      have : (1 : ℤ) ≤ m ^ 2 := by nlinarith [sq_pos_of_ne_zero hm]
      exact_mod_cast this
    linarith [min_le_right lambda1_base (1 / 4)]

/-! ### 4. Monotonicity and Ordering Properties -/

/-- Monotonicity with respect to base eigenvalue:
    $\lambda_{\mathrm{base}, 1} \le \lambda_{\mathrm{base}, 2} \implies \lambda_{1, m} \le \lambda_{2, m}$. -/
theorem casimirEigenvalue_mono_base {l1 l2 : ℝ} (hl : l1 ≤ l2) (m : ℤ) :
    casimirEigenvalue l1 m ≤ casimirEigenvalue l2 m := by
  dsimp [casimirEigenvalue]; linarith

/-- Monotonicity with respect to vertical angular momentum magnitude $|m_1| \le |m_2|$:
    $\lambda_{j, m_1} \le \lambda_{j, m_2}$. -/
theorem casimirEigenvalue_mono_mode (lambda_base : ℝ) {m1 m2 : ℤ}
    (hm : m1.natAbs ≤ m2.natAbs) :
    casimirEigenvalue lambda_base m1 ≤ casimirEigenvalue lambda_base m2 := by
  dsimp [casimirEigenvalue]
  have : (m1 : ℝ) ^ 2 ≤ (m2 : ℝ) ^ 2 := by
    have : (m1.natAbs : ℝ) ≤ m2.natAbs := by exact_mod_cast hm
    nlinarith [show (m1 : ℝ) ^ 2 = (m1.natAbs : ℝ) ^ 2 by simp, show (m2 : ℝ) ^ 2 = (m2.natAbs : ℝ) ^ 2 by simp]
  linarith

end SL2RGeometry
