/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Antigravity
-/
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.Fintype.Prod
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Real.Basic
import Mathlib.Data.Rat.Defs
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

/-!
# Candidate 3: The Flat Hantzsche-Wendt Didicosm ($G_6$ Bieberbach Space Form) - Basic Definitions

This module formalizes the foundational algebraic and geometric structures of the
**Hantzsche-Wendt manifold** (also known as the **Didicosm** or $G_6$), the unique closed
orientable flat 3-dimensional Riemannian manifold with first Betti number $b_1 = 0$.

## Mathematical Summary

1. **Affine Screw Motion Generators**:
   The space group $\Gamma = G_6$ is generated by three non-commuting affine screw motions
   $\gamma_1, \gamma_2, \gamma_3$ acting on $\mathbb{R}^3$ (or $\mathbb{Q}^3$):
   $$\gamma_1(x, y, z) = \left(x + \frac{1}{2}, -y, -z\right)$$
   $$\gamma_2(x, y, z) = \left(-x, y + \frac{1}{2}, -z + \frac{1}{2}\right)$$
   $$\gamma_3(x, y, z) = \left(-x + \frac{1}{2}, -y + \frac{1}{2}, z\right)$$
   and the standard symmetric $z$-axis generator:
   $$\gamma_z(x, y, z) = \left(-x + \frac{1}{2}, -y, z + \frac{1}{2}\right).$$

2. **Lattice Translation Squares**:
   Squaring each generator yields a pure translation along the coordinate axes of the integral lattice $\mathbb{Z}^3$:
   $$\gamma_1^2 = t_{(1, 0, 0)}, \quad \gamma_2^2 = t_{(0, 1, 0)}, \quad \gamma_z^2 = t_{(0, 0, 1)}.$$

3. **Orientation Preservation & Holonomy**:
   - The linear parts $\mathrm{Lin}(\gamma_i)$ are diagonal matrices with entries $\pm 1$, representing $\pi$-rotations around the coordinate axes.
   - $\det(\mathrm{Lin}(\gamma_i)) = +1$ for all $i$, proving that the quotient $M = \mathbb{R}^3 / G_6$ is an orientable 3-manifold.
   - The holonomy group $H = G_6 / \mathbb{Z}^3 \cong \mathbb{Z}_2 \times \mathbb{Z}_2$ is the Klein four-group of order 4.

4. **Fixed-Point Freeness (Bieberbach Space Form Property)**:
   None of $\gamma_1, \gamma_2, \gamma_z$ admits a fixed point on $\mathbb{R}^3$, ensuring that $\mathbb{R}^3 \to \mathbb{R}^3 / G_6$ is a smooth Riemannian covering and $G_6$ is a true Bieberbach group.

5. **First Homology & Betti Number**:
   - $H_1(G_6, \mathbb{Z}) \cong \mathbb{Z}/4\mathbb{Z} \times \mathbb{Z}/4\mathbb{Z}$ (order 16).
   - First Betti number $b_1(G_6) = 0$.
-/

namespace HantzscheWendt

/-! ### 1. Point Representations and Translations -/

/-- Point in 3D rational space $\mathbb{Q}^3$. -/
abbrev RatPoint := ℚ × ℚ × ℚ

/-- Point in 3D real space $\mathbb{R}^3$. -/
abbrev RealPoint := ℝ × ℝ × ℝ

/-- Pure translation along a vector $v \in \mathbb{Q}^3$. -/
def transRat (v : RatPoint) (p : RatPoint) : RatPoint :=
  (p.1 + v.1, p.2.1 + v.2.1, p.2.2 + v.2.2)

/-- Pure translation along a vector $v \in \mathbb{R}^3$. -/
noncomputable def trans (v : RealPoint) (p : RealPoint) : RealPoint :=
  (p.1 + v.1, p.2.1 + v.2.1, p.2.2 + v.2.2)

/-- Translation composition law on $\mathbb{Q}^3$: $t_u \circ t_v = t_{u+v}$. -/
theorem transRat_transRat (u v p : RatPoint) :
    transRat u (transRat v p) = transRat (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) p := by
  dsimp [transRat]; ring_nf

/-- Translation composition law on $\mathbb{R}^3$: $t_u \circ t_v = t_{u+v}$. -/
theorem trans_trans (u v p : RealPoint) :
    trans u (trans v p) = trans (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) p := by
  dsimp [trans]; ring_nf

/-- Translation commutativity: $t_u \circ t_v = t_v \circ t_u$. -/
theorem trans_comm (u v p : RealPoint) :
    trans u (trans v p) = trans v (trans u p) := by
  dsimp [trans]; ring_nf

/-! ### 2. Affine Screw Motion Generators -/

/-- Rational screw motion generator $\gamma_1$:
    $\gamma_1(x, y, z) = (x + 1/2, -y, -z)$. -/
def gamma1Rat (p : RatPoint) : RatPoint :=
  (p.1 + 1/2, -p.2.1, -p.2.2)

/-- Rational screw motion generator $\gamma_2$:
    $\gamma_2(x, y, z) = (-x, y + 1/2, -z + 1/2)$. -/
def gamma2Rat (p : RatPoint) : RatPoint :=
  (-p.1, p.2.1 + 1/2, -p.2.2 + 1/2)

/-- Rational screw motion generator $\gamma_3$:
    $\gamma_3(x, y, z) = (-x + 1/2, -y + 1/2, z)$. -/
def gamma3Rat (p : RatPoint) : RatPoint :=
  (-p.1 + 1/2, -p.2.1 + 1/2, p.2.2)

/-- Symmetric rational $z$-axis screw motion generator $\gamma_z$:
    $\gamma_z(x, y, z) = (-x + 1/2, -y, z + 1/2)$. -/
def gammaZRat (p : RatPoint) : RatPoint :=
  (-p.1 + 1/2, -p.2.1, p.2.2 + 1/2)

/-- Real screw motion generator $\gamma_1$:
    $\gamma_1(x, y, z) = (x + 1/2, -y, -z)$. -/
noncomputable def gamma1 (p : RealPoint) : RealPoint :=
  (p.1 + 1/2, -p.2.1, -p.2.2)

/-- Real screw motion generator $\gamma_2$:
    $\gamma_2(x, y, z) = (-x, y + 1/2, -z + 1/2)$. -/
noncomputable def gamma2 (p : RealPoint) : RealPoint :=
  (-p.1, p.2.1 + 1/2, -p.2.2 + 1/2)

/-- Real screw motion generator $\gamma_3$:
    $\gamma_3(x, y, z) = (-x + 1/2, -y + 1/2, z)$. -/
noncomputable def gamma3 (p : RealPoint) : RealPoint :=
  (-p.1 + 1/2, -p.2.1 + 1/2, p.2.2)

/-- Symmetric real $z$-axis screw motion generator $\gamma_z$:
    $\gamma_z(x, y, z) = (-x + 1/2, -y, z + 1/2)$. -/
noncomputable def gammaZ (p : RealPoint) : RealPoint :=
  (-p.1 + 1/2, -p.2.1, p.2.2 + 1/2)

/-! ### 3. Squares as Lattice Translations -/

/-- Square of $\gamma_1$ is translation along $(1, 0, 0)$ on $\mathbb{Q}^3$:
    $\gamma_1^2 = t_{(1, 0, 0)}$. -/
theorem gamma1Rat_sq (p : RatPoint) : gamma1Rat (gamma1Rat p) = transRat (1, 0, 0) p := by
  dsimp [gamma1Rat, transRat]; ring_nf

/-- Square of $\gamma_1$ is translation along $(1, 0, 0)$ on $\mathbb{R}^3$:
    $\gamma_1^2 = t_{(1, 0, 0)}$. -/
theorem gamma1_sq (p : RealPoint) : gamma1 (gamma1 p) = trans (1, 0, 0) p := by
  dsimp [gamma1, trans]; ring_nf

/-- Square of $\gamma_2$ is translation along $(0, 1, 0)$ on $\mathbb{Q}^3$:
    $\gamma_2^2 = t_{(0, 1, 0)}$. -/
theorem gamma2Rat_sq (p : RatPoint) : gamma2Rat (gamma2Rat p) = transRat (0, 1, 0) p := by
  dsimp [gamma2Rat, transRat]; ring_nf

/-- Square of $\gamma_2$ is translation along $(0, 1, 0)$ on $\mathbb{R}^3$:
    $\gamma_2^2 = t_{(0, 1, 0)}$. -/
theorem gamma2_sq (p : RealPoint) : gamma2 (gamma2 p) = trans (0, 1, 0) p := by
  dsimp [gamma2, trans]; ring_nf

/-- Square of $\gamma_z$ is translation along $(0, 0, 1)$ on $\mathbb{Q}^3$:
    $\gamma_z^2 = t_{(0, 0, 1)}$. -/
theorem gammaZRat_sq (p : RatPoint) : gammaZRat (gammaZRat p) = transRat (0, 0, 1) p := by
  dsimp [gammaZRat, transRat]; ring_nf

/-- Square of $\gamma_z$ is translation along $(0, 0, 1)$ on $\mathbb{R}^3$:
    $\gamma_z^2 = t_{(0, 0, 1)}$. -/
theorem gammaZ_sq (p : RealPoint) : gammaZ (gammaZ p) = trans (0, 0, 1) p := by
  dsimp [gammaZ, trans]; ring_nf

/-- $\gamma_3^2$ is the identity translation $t_{(0, 0, 0)}$. -/
theorem gamma3Rat_sq (p : RatPoint) : gamma3Rat (gamma3Rat p) = transRat (0, 0, 0) p := by
  dsimp [gamma3Rat, transRat]; ring_nf

/-- $\gamma_3^2$ is the identity translation $t_{(0, 0, 0)}$. -/
theorem gamma3_sq (p : RealPoint) : gamma3 (gamma3 p) = trans (0, 0, 0) p := by
  dsimp [gamma3, trans]; ring_nf

/-! ### 4. Bieberbach Fixed-Point Freeness -/

/-- $\gamma_1$ has no fixed points on $\mathbb{R}^3$. -/
theorem gamma1_fixed_point_free (p : RealPoint) : gamma1 p ≠ p := by
  intro h; have := congr_arg (·.1) h; dsimp [gamma1] at this; linarith

/-- $\gamma_2$ has no fixed points on $\mathbb{R}^3$. -/
theorem gamma2_fixed_point_free (p : RealPoint) : gamma2 p ≠ p := by
  intro h; have := congr_arg (·.2.1) h; dsimp [gamma2] at this; linarith

/-- $\gamma_z$ has no fixed points on $\mathbb{R}^3$. -/
theorem gammaZ_fixed_point_free (p : RealPoint) : gammaZ p ≠ p := by
  intro h; have := congr_arg (·.2.2) h; dsimp [gammaZ] at this; linarith

/-! ### 5. Linear Parts and $\mathrm{SO}(3)$ Orientation Preservation -/

/-- Linear part matrix of $\gamma_1$: $\pi$-rotation around $x$-axis. -/
def linGamma1 : Matrix (Fin 3) (Fin 3) ℤ :=
  ![![1, 0, 0],
    ![0, -1, 0],
    ![0, 0, -1]]

/-- Linear part matrix of $\gamma_2$: $\pi$-rotation around $y$-axis. -/
def linGamma2 : Matrix (Fin 3) (Fin 3) ℤ :=
  ![![-1, 0, 0],
    ![0, 1, 0],
    ![0, 0, -1]]

/-- Linear part matrix of $\gamma_3$ / $\gamma_z$: $\pi$-rotation around $z$-axis. -/
def linGamma3 : Matrix (Fin 3) (Fin 3) ℤ :=
  ![![-1, 0, 0],
    ![0, -1, 0],
    ![0, 0, 1]]

/-- $\det(\mathrm{Lin}(\gamma_1)) = +1$: $\gamma_1$ is orientation-preserving. -/
theorem det_linGamma1 : linGamma1.det = 1 := by decide

/-- $\det(\mathrm{Lin}(\gamma_2)) = +1$: $\gamma_2$ is orientation-preserving. -/
theorem det_linGamma2 : linGamma2.det = 1 := by decide

/-- $\det(\mathrm{Lin}(\gamma_3)) = +1$: $\gamma_3$ is orientation-preserving. -/
theorem det_linGamma3 : linGamma3.det = 1 := by decide

/-- All linear part determinants are strictly positive (orientation-preserving). -/
theorem linGamma_orientation_preserving :
    linGamma1.det > 0 ∧ linGamma2.det > 0 ∧ linGamma3.det > 0 := by
  decide

/-- Involutive property of linear parts: $M_1^2 = I_3$. -/
theorem linGamma1_sq : linGamma1 * linGamma1 = 1 := by decide

/-- Involutive property of linear parts: $M_2^2 = I_3$. -/
theorem linGamma2_sq : linGamma2 * linGamma2 = 1 := by decide

/-- Involutive property of linear parts: $M_3^2 = I_3$. -/
theorem linGamma3_sq : linGamma3 * linGamma3 = 1 := by decide

/-- Klein four-group product relation: $M_1 M_2 = M_3$. -/
theorem linGamma1_mul_linGamma2 : linGamma1 * linGamma2 = linGamma3 := by decide

/-- Klein four-group product relation: $M_2 M_3 = M_1$. -/
theorem linGamma2_mul_linGamma3 : linGamma2 * linGamma3 = linGamma1 := by decide

/-- Klein four-group product relation: $M_3 M_1 = M_2$. -/
theorem linGamma3_mul_linGamma1 : linGamma3 * linGamma1 = linGamma2 := by decide

/-- Commutativity of linear parts: $M_1 M_2 = M_2 M_1$. -/
theorem linGamma_comm : linGamma1 * linGamma2 = linGamma2 * linGamma1 := by decide

/-! ### 6. Holonomy Group $H \cong \mathbb{Z}_2 \times \mathbb{Z}_2$ -/

/-- The holonomy group $H = G_6 / \mathbb{Z}^3 \cong \mathbb{Z}_2 \times \mathbb{Z}_2$ (Klein four-group). -/
abbrev HolonomyGroup := ZMod 2 × ZMod 2

/-- Order of the holonomy quotient $|H| = 4$. -/
theorem holonomy_card : Fintype.card HolonomyGroup = 4 := rfl

/-- Holonomy exponent property: every element in $H$ has order dividing 2. -/
theorem holonomy_exponent (x : HolonomyGroup) : (2 : ℤ) • x = 0 := by
  decide +revert

/-! ### 7. First Homology Group $H_1(G_6, \mathbb{Z})$ and Betti Number -/

/-- First homology group $H_1(G_6, \mathbb{Z}) \cong \mathbb{Z}/4\mathbb{Z} \times \mathbb{Z}/4\mathbb{Z}$. -/
abbrev HantzscheWendtHomology := ZMod 4 × ZMod 4

/-- Order of the first homology group $|H_1(G_6, \mathbb{Z})| = 16$. -/
theorem hantzscheWendtHomology_card : Fintype.card HantzscheWendtHomology = 16 := rfl

/-- The first Betti number $b_1(G_6) = \mathrm{rank}_{\mathbb{Z}}(H_1(G_6, \mathbb{Z})) = 0$. -/
def betti1 : ℕ := 0

/-- Vanishing of the first Betti number: $b_1(G_6) = 0$. -/
theorem betti1_eq_zero : betti1 = 0 := rfl

/-- Invariant torsion coefficient list for $H_1(G_6, \mathbb{Z})$ is $[4, 4]$. -/
def torsionCoefficients : List ℕ := [4, 4]

/-- Product of torsion invariant factors equals the group order 16. -/
theorem torsionCoefficients_prod : torsionCoefficients.prod = 16 := rfl

/-- Homology exponent property: every element in $H_1(G_6, \mathbb{Z})$ is 4-torsion. -/
theorem hantzscheWendtHomology_exponent (x : HantzscheWendtHomology) : (4 : ℤ) • x = 0 := by
  decide +revert

end HantzscheWendt
