/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Antigravity
-/
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.BigOperators.Intervals
import Mathlib.Algebra.Group.Basic
import Mathlib.Tactic.IntervalCases

open BigOperators

/-!
# Pillar 7: $\mathbb{S}^2 \times \mathbb{R}$ Geometry - Basic Topology & Homology

This module formalizes the foundational topological structure of the compact 3-manifold
$M = S^2 \times S^1_L$ (with circle circumference $L > 0$), which is the standard compact
quotient of the Thurston model geometry $\mathbb{S}^2 \times \mathbb{R}$.

## Mathematical Summary

1. **Product Manifold Structure**:
   - The universal covering space is the Riemannian product $\mathbb{S}^2 \times \mathbb{R}$.
   - The deck transformation group is $\Gamma \cong \mathbb{Z}$, acting by translations along the $\mathbb{R}$ factor:
     $$\gamma_n(p, z) = (p, z + n L), \quad n \in \mathbb{Z}, \; p \in S^2, \; z \in \mathbb{R}.$$
   - The compact quotient is $M = S^2 \times S^1_L$ where $S^1_L = \mathbb{R} / L\mathbb{Z}$.

2. **Fundamental Group**:
   - By the product property of homotopy groups:
     $$\pi_1(S^2 \times S^1) \cong \pi_1(S^2) \times \pi_1(S^1) \cong 0 \times \mathbb{Z} \cong \mathbb{Z}.$$
   - It is infinite cyclic, generated by the canonical winding loop $\gamma \in \pi_1(S^2 \times S^1)$.

3. **Homology Groups (Künneth Formula)**:
   - Since $H_*(S^2; \mathbb{Z})$ and $H_*(S^1; \mathbb{Z})$ are torsion-free, the Künneth formula gives:
     $$H_k(S^2 \times S^1; \mathbb{Z}) \cong \bigoplus_{i+j=k} H_i(S^2; \mathbb{Z}) \otimes_{\mathbb{Z}} H_j(S^1; \mathbb{Z}).$$
   - Explicit homology groups:
     - $H_0(S^2 \times S^1, \mathbb{Z}) \cong \mathbb{Z}$ (connected)
     - $H_1(S^2 \times S^1, \mathbb{Z}) \cong \mathbb{Z}$ (circle factor)
     - $H_2(S^2 \times S^1, \mathbb{Z}) \cong \mathbb{Z}$ (sphere factor)
     - $H_3(S^2 \times S^1, \mathbb{Z}) \cong \mathbb{Z}$ (fundamental class / orientation)
     - $H_k(S^2 \times S^1, \mathbb{Z}) \cong 0$ for all $k \ge 4$.

4. **Betti Numbers**:
   - $b_0 = 1, \; b_1 = 1, \; b_2 = 1, \; b_3 = 1$, and $b_k = 0$ for $k \ge 4$.
   - Künneth convolution identity: $b_k(S^2 \times S^1) = \sum_{i=0}^k b_i(S^2) b_{k-i}(S^1)$.

5. **Euler Characteristic & Poincaré Duality**:
   - Product formula: $\chi(S^2 \times S^1) = \chi(S^2) \cdot \chi(S^1) = 2 \cdot 0 = 0$.
   - Alternating Betti sum: $\chi = b_0 - b_1 + b_2 - b_3 = 1 - 1 + 1 - 1 = 0$.
   - Poincaré duality: $b_k = b_{3-k}$ for all $0 \le k \le 3$.
-/

namespace S2xRGeometry

/-! ### 1. Manifold Parameters and Fundamental Group -/

/-- Geometric parameter specifying the compact circle length $L > 0$. -/
structure ManifoldParam where
  L : ℝ
  hL : L > 0

/-- The fundamental group $\pi_1(S^2 \times S^1) \cong \mathbb{Z}$, generated by the winding loop around $S^1$. -/
@[ext]
structure Pi1 where
  winding : ℤ
  deriving DecidableEq, Repr

/-- Group multiplication in $\pi_1(S^2 \times S^1)$: composition of winding loops. -/
def mul (g1 g2 : Pi1) : Pi1 := ⟨g1.winding + g2.winding⟩

instance : Mul Pi1 := ⟨mul⟩

/-- Identity element of $\pi_1(S^2 \times S^1)$: the contractible loop. -/
def one : Pi1 := ⟨0⟩

instance : One Pi1 := ⟨one⟩

/-- Group inverse in $\pi_1(S^2 \times S^1)$: loop reversal. -/
def inv (g : Pi1) : Pi1 := ⟨-g.winding⟩

instance : Inv Pi1 := ⟨inv⟩

@[simp] theorem mul_winding (a b : Pi1) : (a * b).winding = a.winding + b.winding := rfl
@[simp] theorem one_winding : (1 : Pi1).winding = 0 := rfl
@[simp] theorem inv_winding (a : Pi1) : a⁻¹.winding = -a.winding := rfl

instance : CommGroup Pi1 where
  mul_assoc _ _ _ := Pi1.ext (add_assoc _ _ _)
  one_mul _ := Pi1.ext (zero_add _)
  mul_one _ := Pi1.ext (add_zero _)
  inv_mul_cancel _ := Pi1.ext (neg_add_cancel _)
  mul_comm _ _ := Pi1.ext (add_comm _ _)

/-- The canonical group isomorphism between $\pi_1(S^2 \times S^1)$ and $(\mathbb{Z}, +)$. -/
def pi1EquivInt : Pi1 ≃* Multiplicative ℤ where
  toFun g := Multiplicative.ofAdd g.winding
  invFun n := ⟨Multiplicative.toAdd n⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_mul' _ _ := rfl

/-- Canonical generator of $\pi_1(S^2 \times S^1)$ corresponding to 1 winding loop around $S^1$. -/
def genLoop : Pi1 := ⟨1⟩

@[simp] theorem genLoop_winding : genLoop.winding = 1 := rfl

/-- Power of the canonical generator corresponds to the integer winding number. -/
theorem zpow_genLoop (n : ℤ) : genLoop ^ n = ⟨n⟩ := by
  induction n using Int.induction_on with
  | zero => rfl
  | succ i ih => ext; rw [zpow_add_one, ih]; simp [genLoop]
  | pred i ih => ext; rw [zpow_sub_one, ih]; simp [sub_eq_add_neg, genLoop]

/-- The fundamental group is infinite cyclic (generated by a single element). -/
theorem pi1_is_cyclic (g : Pi1) : ∃ n : ℤ, g = genLoop ^ n :=
  ⟨g.winding, (zpow_genLoop g.winding).symm⟩

/-! ### 2. Betti Numbers and Factor Spaces -/

/-- Betti numbers of the 2-sphere $S^2$: $b_0 = 1, b_1 = 0, b_2 = 1$, and $b_k = 0$ for $k \ge 3$. -/
def bettiS2 (k : ℕ) : ℕ :=
  if k = 0 then 1
  else if k = 2 then 1
  else 0

@[simp] theorem bettiS2_zero : bettiS2 0 = 1 := rfl
@[simp] theorem bettiS2_one : bettiS2 1 = 0 := rfl
@[simp] theorem bettiS2_two : bettiS2 2 = 1 := rfl
theorem bettiS2_ge_three (k : ℕ) (hk : k ≥ 3) : bettiS2 k = 0 := by
  dsimp [bettiS2]; split_ifs <;> omega

/-- Betti numbers of the circle $S^1$: $b_0 = 1, b_1 = 1$, and $b_k = 0$ for $k \ge 2$. -/
def bettiS1 (k : ℕ) : ℕ :=
  if k = 0 then 1
  else if k = 1 then 1
  else 0

@[simp] theorem bettiS1_zero : bettiS1 0 = 1 := rfl
@[simp] theorem bettiS1_one : bettiS1 1 = 1 := rfl
theorem bettiS1_ge_two (k : ℕ) (hk : k ≥ 2) : bettiS1 k = 0 := by
  dsimp [bettiS1]; split_ifs <;> omega

/-- Euler characteristic of $S^2$: $\chi(S^2) = b_0 - b_1 + b_2 = 1 - 0 + 1 = 2$. -/
def eulerS2 : ℤ := (bettiS2 0 : ℤ) - (bettiS2 1 : ℤ) + (bettiS2 2 : ℤ)

@[simp] theorem eulerS2_eq_two : eulerS2 = 2 := rfl

/-- Euler characteristic of $S^1$: $\chi(S^1) = b_0 - b_1 = 1 - 1 = 0$. -/
def eulerS1 : ℤ := (bettiS1 0 : ℤ) - (bettiS1 1 : ℤ)

@[simp] theorem eulerS1_eq_zero : eulerS1 = 0 := rfl

/-! ### 3. Product Betti Numbers & Künneth Formula -/

/-- Betti numbers of the product manifold $S^2 \times S^1$:
    $b_0 = 1, b_1 = 1, b_2 = 1, b_3 = 1$, and $b_k = 0$ for $k \ge 4$. -/
def betti (k : ℕ) : ℕ :=
  if k ≤ 3 then 1 else 0

@[simp] theorem betti_zero : betti 0 = 1 := rfl
@[simp] theorem betti_one : betti 1 = 1 := rfl
@[simp] theorem betti_two : betti 2 = 1 := rfl
@[simp] theorem betti_three : betti 3 = 1 := rfl

theorem betti_ge_four (k : ℕ) (hk : k ≥ 4) : betti k = 0 := by
  dsimp [betti]; split_ifs <;> omega

/-- Künneth convolution product for Betti numbers:
    $$b_k(S^2 \times S^1) = \sum_{i=0}^k b_i(S^2) b_{k-i}(S^1).$$ -/
def kunnethBetti (k : ℕ) : ℕ :=
  Finset.sum (Finset.range (k + 1)) (fun i => bettiS2 i * bettiS1 (k - i))

theorem kunneth_betti_zero : kunnethBetti 0 = betti 0 := rfl
theorem kunneth_betti_one : kunnethBetti 1 = betti 1 := rfl
theorem kunneth_betti_two : kunnethBetti 2 = betti 2 := rfl
theorem kunneth_betti_three : kunnethBetti 3 = betti 3 := rfl

theorem kunneth_betti_ge_four (k : ℕ) (hk : k ≥ 4) : kunnethBetti k = 0 :=
  Finset.sum_eq_zero fun _ _ => by dsimp [bettiS2, bettiS1]; split_ifs <;> omega

/-- Künneth Theorem on Betti Numbers:
    The Künneth convolution matches the Betti numbers for all dimensions $k \in \mathbb{N}$. -/
theorem kunneth_betti_eq (k : ℕ) : kunnethBetti k = betti k := by
  rcases lt_or_ge k 4 with hk | hk
  · interval_cases k <;> rfl
  · rw [kunneth_betti_ge_four k hk, betti_ge_four k hk]

/-! ### 4. Homology Group Ranks -/

/-- Homology rank $\mathrm{rank}_{\mathbb{Z}}(H_k(S^2 \times S^1, \mathbb{Z}))$. -/
def homologyRank (k : ℕ) : ℕ := betti k

@[simp] theorem H0_rank : homologyRank 0 = 1 := rfl
@[simp] theorem H1_rank : homologyRank 1 = 1 := rfl
@[simp] theorem H2_rank : homologyRank 2 = 1 := rfl
@[simp] theorem H3_rank : homologyRank 3 = 1 := rfl
theorem H_ge_four_rank (k : ℕ) (hk : k ≥ 4) : homologyRank k = 0 := betti_ge_four k hk

/-! ### 5. Euler Characteristic & Poincaré Duality -/

/-- Total Euler characteristic of $S^2 \times S^1$ computed as the alternating sum of Betti numbers:
    $$\chi(S^2 \times S^1) = b_0 - b_1 + b_2 - b_3 = 1 - 1 + 1 - 1 = 0.$$ -/
def eulerChar : ℤ :=
  (betti 0 : ℤ) - (betti 1 : ℤ) + (betti 2 : ℤ) - (betti 3 : ℤ)

/-- Euler characteristic of $S^2 \times S^1$ is identically zero. -/
theorem eulerChar_eq_zero : eulerChar = 0 := rfl

/-- Multiplicativity of Euler characteristic: $\chi(S^2 \times S^1) = \chi(S^2) \cdot \chi(S^1) = 2 \cdot 0 = 0$. -/
theorem eulerChar_product : eulerChar = eulerS2 * eulerS1 := rfl

/-- Poincaré Duality on Betti numbers: $b_k = b_{3-k}$ for all $0 \le k \le 3$. -/
theorem poincare_duality (k : ℕ) (hk : k ≤ 3) : betti k = betti (3 - k) := by
  interval_cases k <;> rfl

end S2xRGeometry